server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    url: jdbc:h2:mem:coursedb
    username: sa
    password:
logging:
  level:
    org.springframework: DEBUG
