spring:
  application:
    name: course-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://mysql:3306/coursedb}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DATASOURCE_USERNAME:course}
    password: ${DATASOURCE_PASSWORD:course123}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    org.springframework: INFO
