spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://mysql:3306/coursedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: course
    password: course123
  jpa:
    hibernate:
      ddl-auto: update
