spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/gateway_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Distributed Tracing Configuration
  zipkin:
    base-url: http://localhost:9411
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-service
          uri: lb://gateway-service
          predicates:
            - Path=/auth/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/students/**
        - id: progress-service
          uri: lb://progress-service
          predicates:
            - Path=/progress/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
jwt:
  secret: mySecretKey
  expiration: 86400000

# Additional Tracing Configuration
zipkin:
  base-url: http://localhost:9411

logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud.sleuth: DEBUG
