spring:
  application:
    name: progress-service
  datasource:
    url: jdbc:mysql://mysql:3306/progressdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: progress
    password: progress123
  jpa:
    hibernate:
      ddl-auto: update
