server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    username: sa
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    org.springframework: DEBUG
