<<<<<<< HEAD
server:
  port: 8082
=======
>>>>>>> 18b3f5cbe4e2b027e2f5f420a9624f9ff2fb6d3d
spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    username: sa
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    org.springframework: DEBUG
