spring:
  datasource:
<<<<<<< HEAD
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/studentdb}
    username: ${DATASOURCE_USERNAME:student_user}
    password: ${DATASOURCE_PASSWORD:student_pass}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
=======
    url: jdbc:postgresql://localhost:5432/studentdb
    username: student_user
    password: student_pass
>>>>>>> 18b3f5cbe4e2b027e2f5f420a9624f9ff2fb6d3d
logging:
  level:
    org.springframework: INFO
